# Generated by Django 5.2.15 on 2026-06-20 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0007_specialization_alter_clinic_options_and_more'),
        ('pets', '0004_petdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vetmanager', 'Vetmanager (REST API)'), ('onec', '1С:Медицина. Ветклиника'), ('webhook', 'Generic webhook + REST'), ('fhir', 'HL7 FHIR')], max_length=20, verbose_name='Тип МИС')),
                ('base_url', models.URLField(blank=True, max_length=500, verbose_name='Base URL API')),
                ('api_token', models.CharField(blank=True, help_text='Если МИС использует static-токен. Для OAuth — client_secret.', max_length=255, verbose_name='API-токен / OAuth secret')),
                ('oauth_client_id', models.CharField(blank=True, max_length=128, verbose_name='OAuth client_id')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Произвольный JSON: db_name для 1С, scope, иные настройки адаптера.', verbose_name='Дополнительные параметры')),
                ('webhook_secret', models.CharField(blank=True, help_text='Используется для подписи входящих POST. Генерируется автоматически.', max_length=64, verbose_name='Webhook secret (HMAC SHA-256)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('push_appointments', models.BooleanField(default=True, verbose_name='Слать заявки в МИС')),
                ('pull_schedule', models.BooleanField(default=True, verbose_name='Тянуть расписание')),
                ('pull_visits', models.BooleanField(default=True, verbose_name='Тянуть итоги визитов')),
                ('pull_services', models.BooleanField(default=True, verbose_name='Тянуть прайс')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='clinics.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Интеграция клиники',
                'verbose_name_plural': 'Интеграции клиник',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(verbose_name='Дата визита')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='Лечение / назначения')),
                ('services_done', models.JSONField(blank=True, default=list, help_text='[{"name": "...", "price": 1500}, ...]', verbose_name='Услуги')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого, ₽')),
                ('documents', models.JSONField(blank=True, default=list, help_text='[{"url": "...", "title": "..."}, ...]', verbose_name='Документы')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='id в МИС')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырой payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='appointments.appointment', verbose_name='Запись')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='integrations.clinicintegration')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='pets.pet')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_done', to='clinics.vetprofile')),
            ],
            options={
                'verbose_name': 'Визит (из МИС)',
                'verbose_name_plural': 'Визиты (из МИС)',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_kind', models.CharField(max_length=64, verbose_name='Локальный объект')),
                ('local_id', models.PositiveBigIntegerField(verbose_name='Локальный id')),
                ('external_id', models.CharField(max_length=128, verbose_name='id в МИС')),
                ('external_kind', models.CharField(blank=True, max_length=64, verbose_name='Тип в МИС')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.clinicintegration')),
            ],
            options={
                'verbose_name': 'Внешний id',
                'verbose_name_plural': 'Внешние id (mapping)',
                'unique_together': {('integration', 'local_kind', 'external_id'), ('integration', 'local_kind', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Исходящее'), ('in', 'Входящее')], max_length=4, verbose_name='Направление')),
                ('kind', models.CharField(help_text='appointment_push, schedule_pull, visit_in, ...', max_length=64, verbose_name='Событие')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Ошибка'), ('retry', 'Повтор')], default='ok', max_length=8, verbose_name='Статус')),
                ('http_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP-код')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Тело')),
                ('response', models.JSONField(blank=True, default=dict, verbose_name='Ответ')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.clinicintegration', verbose_name='Интеграция')),
            ],
            options={
                'verbose_name': 'Событие интеграции',
                'verbose_name_plural': 'События интеграции',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integration', '-created_at'], name='integration_integra_b78402_idx'), models.Index(fields=['kind', 'status'], name='integration_kind_5b5915_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='Начало')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, verbose_name='Длительность, мин')),
                ('is_available', models.BooleanField(default=True, verbose_name='Свободен')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='id в МИС')),
                ('pulled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Получен')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='integrations.clinicintegration')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='clinics.vetprofile', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Слот расписания',
                'verbose_name_plural': 'Слоты расписания',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['vet', 'starts_at'], name='integration_vet_id_5548d8_idx'), models.Index(fields=['is_available', 'starts_at'], name='integration_is_avai_e7cf40_idx')],
                'unique_together': {('integration', 'external_id')},
            },
        ),
    ]
