# Generated by Django 5.2.8 on 2026-04-08 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'user_type__in': ['clinic_admin', 'vet']}, related_name='managed_clinics', to=settings.AUTH_USER_MODEL, verbose_name='Администраторы'),
        ),
    ]
