# Generated by Django 5.2.8 on 2026-04-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Рейтинг от 0 до 5', max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='reviews',
            field=models.TextField(blank=True, help_text='Отзывы клиентов о клинике', verbose_name='Отзывы'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='working_hours',
            field=models.TextField(blank=True, help_text='Например: Пн-Пт 9:00-20:00, Сб-Вс 10:00-18:00', verbose_name='Часы работы'),
        ),
    ]
