# Generated by Django 5.2.8 on 2026-04-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_rating_clinic_reviews_clinic_working_hours'),
        ('clinics', '0003_clinic_rating_clinic_reviews_clinic_working_hours_and_more'),
    ]

    operations = [
    ]
