# Generated by Django 5.2.8 on 2026-04-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_merge_20260415_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='reviews',
            field=models.TextField(blank=True, help_text='Отзывы клиентов о клинике (если нет ID Яндекс Карт)', verbose_name='Отзывы'),
        ),
    ]
