# Generated by Django 5.2.15 on 2026-06-19 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_clinic_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Слаг')),
                ('icon', models.CharField(blank=True, default='🩺', max_length=8, verbose_name='Эмодзи-иконка')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['-rating', 'name'], 'verbose_name': 'Клиника', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.AddField(
            model_name='clinic',
            name='accepts_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн-консультации'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='has_lab',
            field=models.BooleanField(default=False, verbose_name='Своя лаборатория'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='has_surgery',
            field=models.BooleanField(default=False, verbose_name='Хирургия'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_24h',
            field=models.BooleanField(default=False, verbose_name='Круглосуточно'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clinics/photos/', verbose_name='Фото клиники'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Отзывов'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг (агрегат)'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='reviews',
            field=models.TextField(blank=True, verbose_name='Отзывы (legacy)'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='yandex_maps_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Яндекс Карт'),
        ),
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vets/photos/', verbose_name='Фото')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт, лет')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('price_consultation', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена приёма, ₽')),
                ('accepts_online', models.BooleanField(default=False, verbose_name='Онлайн-консультации')),
                ('accepts_house_call', models.BooleanField(default=False, verbose_name='Выезд на дом')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг (агрегат)')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Отзывов')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публиковать в каталоге')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vets', to='clinics.clinic', verbose_name='Клиника')),
                ('specializations', models.ManyToManyField(blank=True, related_name='vets', to='clinics.specialization', verbose_name='Специализации')),
                ('user', models.OneToOneField(limit_choices_to={'user_type__in': ['vet', 'clinic_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='vet_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учётка')),
            ],
            options={
                'verbose_name': 'Профиль врача',
                'verbose_name_plural': 'Профили врачей',
                'ordering': ['-rating', 'user__last_name'],
            },
        ),
    ]
