# Generated by Django 5.2.8 on 2026-04-08 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceassignment',
            name='vet',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['vet', 'clinic_admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ветеринар'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceassignment',
            unique_together={('service', 'vet')},
        ),
    ]
