# Generated by Django 5.2.8 on 2026-04-08 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('bird', 'Птица'), ('rodent', 'Грызун'), ('rabbit', 'Кролик'), ('reptile', 'Рептилия'), ('other', 'Другое')], max_length=20, verbose_name='Вид')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='Порода')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('chip_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер чипа')),
                ('qr_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID для QR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['name'],
            },
        ),
    ]
