# Generated by Django 5.2.15 on 2026-06-19 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0007_specialization_alter_clinic_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('pros', models.CharField(blank=True, max_length=300, verbose_name='Плюсы')),
                ('cons', models.CharField(blank=True, max_length=300, verbose_name='Минусы')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('clinic_reply', models.TextField(blank=True, verbose_name='Ответ клиники')),
                ('clinic_reply_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_reviews', to='clinics.clinic', verbose_name='Клиника')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vet_reviews', to='clinics.vetprofile', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('clinic__isnull', False), ('vet__isnull', True)), models.Q(('clinic__isnull', True), ('vet__isnull', False)), _connector='OR'), name='review_target_xor')],
            },
        ),
    ]
