# Generated by Django 5.2.15 on 2026-06-19 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0007_specialization_alter_clinic_options_and_more'),
        ('pets', '0004_petdocument'),
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время')),
                ('kind', models.CharField(choices=[('offline', 'В клинике'), ('online', 'Онлайн'), ('house_call', 'На дому')], default='offline', max_length=20, verbose_name='Формат')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('confirmed', 'Подтверждена'), ('done', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина обращения')),
                ('vet_note', models.TextField(blank=True, verbose_name='Заметка врача')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinics.clinic', verbose_name='Клиника')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='pets.pet', verbose_name='Питомец')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service', verbose_name='Услуга')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.vetprofile', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['vet', 'scheduled_at'], name='appointment_vet_id_d349bc_idx'), models.Index(fields=['owner', 'scheduled_at'], name='appointment_owner_i_cd97d9_idx')],
            },
        ),
    ]
